struct LayerParams {
    dst_x: f32,
    dst_y: f32,
    dst_w: f32,
    dst_h: f32,
    src_x: f32,
    src_y: f32,
    src_w: f32,
    src_h: f32,
    crop_x: f32,
    crop_y: f32,
    crop_w: f32,
    crop_h: f32,
    source_aspect: f32,
    frame_w: f32,
    frame_h: f32,
    opacity: f32,
    exposure: f32,
    black: f32,
    brightness: f32,
    contrast: f32,
    saturation: f32,
    vibrance: f32,
    temperature: f32,
    tint: f32,
    highlights: f32,
    shadows: f32,
    whites: f32,
    blacks: f32,
    clarity: f32,
    texture: f32,
    sharpen: f32,
    denoise: f32,
    grade_shadows_hue: f32,
    grade_shadows_amount: f32,
    grade_mid_hue: f32,
    grade_mid_amount: f32,
    grade_highlights_hue: f32,
    grade_highlights_amount: f32,
    curve_lift: f32,
    curve_contrast: f32,
    levels_black: f32,
    levels_gray: f32,
    levels_white: f32,
    curve_rgb_count: f32,
    curve_luminance_count: f32,
    curve_red_count: f32,
    curve_green_count: f32,
    curve_blue_count: f32,
    texel_x: f32,
    texel_y: f32,
    orientation: f32,
    rotate: f32,
    flip_h: f32,
    flip_v: f32,
    scale: f32,
    translate_x: f32,
    translate_y: f32,
    lut_size: f32,
    lut_intensity: f32,
    sampling_quality: f32,
    procedural: vec4<f32>,
    fill_rgba: vec4<f32>,
    stroke_rgba: vec4<f32>,
    text_meta: vec4<f32>,
    text_data: array<vec4<f32>, 32>,
    curve_data: array<vec4<f32>, 30>,
    hsl_data: array<vec4<f32>, 12>,
}

@group(0) @binding(0) var src_texture: texture_2d<f32>;
@group(0) @binding(1) var src_sampler: sampler;
@group(0) @binding(2) var<uniform> params: LayerParams;
@group(0) @binding(3) var lut_texture: texture_3d<f32>;
@group(0) @binding(4) var lut_sampler: sampler;
